// <auto-generated />
namespace project2BurgerMenu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig91 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig91));
        
        string IMigrationMetadata.Id
        {
            get { return "202410232038339_mig91"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
