// <auto-generated />
namespace project2BurgerMenu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig9));
        
        string IMigrationMetadata.Id
        {
            get { return "202410232009040_mig9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
